### ISSUE TITLE
TypeError: lutils.getOptions is not a function

### ISSUE THREAD

**Issue by lvonk** [jhamlet/svg-react-loader#70]
In version 0.4.1 with webpack 2.6.1.

There is no `getOptions` function in the included version of `loader-utils`. I tested using npm-shrinkwrap in using version `1.1.0` of loader-utils and that works with webpack 2.6.1.

**Comment by jhamlet** [comment]
@ivonk thanks.
